name = "Example Property (1000)"

# TODO: display: details (default), summary, balance?
[[groups]]
name = "1001"
codes = ["1001-0000"]

[[groups]]
name = "1002"
codes = ["1002-0000"]

[[groups]]
name = "1003"
codes = ["1003-0000"]

[[groups]]
name = "1004"
codes = ["1002-0000"]

[[groups]]
name = "1005"
start = "1005-0000"
end = "1005-5000"

[[groups]]
name = "Scary Accounts!"
start = "1010-0000"
end = "1030-0000"

[[groups]]
name = "Balancer"
codes = ["1500-0000"]